### ISSUE TITLE
Server crash on login

### ISSUE THREAD

**Issue by MrPowerGamerBR** [Akarin-project/Akarin#15]
```
[09:08:06 INFO]: UUID of player MrPowerGamerBR is 5dcb9cb4-3851-49f9-9a87-13fc62285ab6
[09:08:06 WARN]: Failed to handle packet for /my ip:57017
java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_172]
        at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_172]
        at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_172]
        at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_172]
        at java.util.Formatter.parse(Formatter.java:2547) ~[?:1.8.0_172]
        at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_172]
        at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_172]
        at java.lang.String.format(String.java:2940) ~[?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.LocaleLanguage.a(SourceFile:98) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.LocaleI18n.a(SourceFile:17) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.PlayerList.a(PlayerList.java:184) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.LoginListener.b(LoginListener.java:178) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.LoginListener.e(LoginListener.java:68) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.NetworkManager.a(NetworkManager.java:271) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:150) [server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:945) [server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) [server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:771) [server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:669) [server.jar:git-Akarin-"671c5fb"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[09:08:06 INFO]: MrPowerGamerBR lost connection: Internal server error
[09:08:06 ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
        at java.util.regex.Matcher.getTextLength(Matcher.java:1283) ~[?:1.8.0_172]
        at java.util.regex.Matcher.reset(Matcher.java:309) ~[?:1.8.0_172]
        at java.util.regex.Matcher.<init>(Matcher.java:229) ~[?:1.8.0_172]
        at java.util.regex.Pattern.matcher(Pattern.java:1093) ~[?:1.8.0_172]
        at java.util.Formatter.parse(Formatter.java:2547) ~[?:1.8.0_172]
        at java.util.Formatter.format(Formatter.java:2501) ~[?:1.8.0_172]
        at java.util.Formatter.format(Formatter.java:2455) ~[?:1.8.0_172]
        at java.lang.String.format(String.java:2940) ~[?:1.8.0_172]
        at net.minecraft.server.v1_12_R1.LocaleLanguage.a(SourceFile:98) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.LocaleI18n.a(SourceFile:17) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:444) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1173) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.NetworkManager.handleDisconnection(NetworkManager.java:357) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.ServerConnection.c(ServerConnection.java:184) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:945) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:771) ~[server.jar:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:669) [server.jar:git-Akarin-"671c5fb"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[09:08:06 ERROR]: This crash report has been saved to: /home/servers/perfectdreams/lobby/./crash-reports/crash-2018-07-01_09.08.06-server.txt
```

**Crash log:** https://gist.github.com/MrPowerGamerBR/92a4c0cb344a8ac6283c2f5914f0f95b

**Comment by cakoyo** [comment]
may you paste your akarin.yml?

**Comment by MrPowerGamerBR** [comment]
Uhhhh it seems the file wasn't generated at all! However I'm sure I was running Akarin because `/version` shown that Akarin was running.

**Comment by MrPowerGamerBR** [comment]
Found the issue, I don't run the server JAR via the "conventional" `-jar` way, I add the JAR to the classpath and then run the main class by that. I do this so I can add JARs to the classpath without shading dependencies on other plugins.

And what caused the issue is because I was using `org.bukkit.craftbukkit.Main` as the main class, not `net.minecraft.launchwrapper.Launch`!

However **now** I'm having another different issue:
```
[09:58:07 INFO]: UUID of player MrPowerGamerBR is 5dcb9cb4-3851-49f9-9a87-13fc62285ab6
[09:58:07 INFO]: MrPowerGamerBR[/my ip:43653] logged in with entity id 3 at ([world]0.5, 20.0, 0.5)
[09:58:07 ERROR]: Encountered an unexpected exception
java.lang.UnsupportedOperationException: null
        at java.util.AbstractCollection.add(AbstractCollection.java:262) ~[?:1.8.0_172]
        at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTrackerEntry.addTrackedPlayer(SpigotEntityTrackerEntry.java:581) ~[?:?]
        at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTrackerEntry.updatePlayer(SpigotEntityTrackerEntry.java:365) ~[?:?]
        at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:287) ~[EntityTracker.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.PlayerChunk.b(PlayerChunk.java:161) ~[PlayerChunk.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.PlayerChunkMap.flush(PlayerChunkMap.java:214) ~[PlayerChunkMap.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.tickUnsafeSync(MinecraftServer.java:2002) ~[MinecraftServer.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:1975) ~[MinecraftServer.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[DedicatedServer.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:771) ~[MinecraftServer.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:669) [MinecraftServer.class:git-Akarin-"bbd1057"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
[09:58:07 ERROR]: This crash report has been saved to: /home/servers/perfectdreams/lobby/./crash-reports/crash-2018-07-02_09.58.07-server.txt
```

...and then...

```
[09:58:07 ERROR]: Exception stopping the server
net.minecraft.server.v1_12_R1.ReportedException: Ticking player
        at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:437) ~[EntityPlayer.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.PlayerList.disconnect(PlayerList.java:448) ~[PlayerList.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1173) ~[PlayerConnection.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.PlayerConnection.disconnect(PlayerConnection.java:283) ~[PlayerConnection.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.PlayerList.u(PlayerList.java:1418) ~[PlayerList.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.stop(MinecraftServer.java:499) ~[MinecraftServer.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:705) [MinecraftServer.class:git-Akarin-"bbd1057"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.UnsupportedOperationException
        at java.util.AbstractCollection.add(AbstractCollection.java:262) ~[?:1.8.0_172]
        at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTrackerEntry.addTrackedPlayer(SpigotEntityTrackerEntry.java:581) ~[?:?]
        at protocolsupport.zplatform.impl.spigot.entitytracker.SpigotEntityTrackerEntry.updatePlayer(SpigotEntityTrackerEntry.java:365) ~[?:?]
        at net.minecraft.server.v1_12_R1.EntityTracker.a(EntityTracker.java:240) ~[EntityTracker.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.EntityPlayer.G(EntityPlayer.java:1396) ~[EntityPlayer.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.EntityLiving.tickPotionEffects(EntityLiving.java:591) ~[EntityLiving.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.EntityLiving.Y(EntityLiving.java:307) ~[EntityLiving.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.Entity.B_(Entity.java:339) ~[Entity.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.EntityLiving.B_(EntityLiving.java:1915) ~[EntityLiving.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.EntityHuman.B_(EntityHuman.java:146) ~[EntityHuman.class:git-Akarin-"bbd1057"]
        at net.minecraft.server.v1_12_R1.EntityPlayer.playerTick(EntityPlayer.java:356) ~[EntityPlayer.class:git-Akarin-"bbd1057"]
        ... 7 more
```

**Crash log:** https://gist.github.com/MrPowerGamerBR/f0762c07d418a3d6dc137c0062ada69a

**akarin.yml:**
```
# This is the global configuration file for Akarin.
# Some options may impact gameplay, so use with caution,
# and make sure you know what each option does before configuring.
# 
# Akarin forums: https://akarin.io/ 

config-version: 1
alternative:
  legacy-versioning-compat: false
  legacy-world-timings-required: false
  gc-before-stuck-restart: true
  allow-spawner-modify: true
  modified-server-brand-name: ''
  disable-end-portal-create: false
  version-update-interval: 3600s
core:
  players-per-chunk-io-thread: 50
  always-silent-async-timing: false
  tick-rate:
    world-time-update-interval: 1s
    keep-alive-packet-send-interval: 15s
    players-info-update-interval: 30s
  keep-alive-response-timeout: 30s
  thread-safe:
    async-catcher:
      throw-on-caught: true
  primary-thread-priority: 7
  send-light-only-chunk-sections: true
  async-lighting:
    enable: true
  enable-panda-redstone-wire: true
  enable-real-time-ticking: false
bootstrap:
  extra-local-address: []
messages:
  disconnect:
    kick-player: Kicked by an operator.
    ban-player-name: You are banned from this server! %s %s
    ban-reason: "\nReason: "
    ban-expires: "\nYour ban will be removed on "
    ban-player-ip: Your IP address is banned from this server! %s %s
    kick-player-duplicate-login: You logged in from another location
    player-quit-server: §e%s left the game
    kick-player-timeout-keep-alive: Timed out
  connect:
    player-join-server: §e%s joined the game
    renamed-player-join-server: §e%s (formerly known as %s) joined the game
```

**Comment by MrPowerGamerBR** [comment]
This seems to be caused due to an incompatibility with [ProtocolSupport](https://github.com/ProtocolSupport/ProtocolSupport), without ProtocolSupport the crash doesn't happen.

**Comment by MrPowerGamerBR** [comment]
...it seems the ProtocolSupport version I had on the server was outdated, whoops! Updating ProtocolSupport fixed the issue.
