### ISSUE TITLE
airbar just keeps crashing

### ISSUE THREAD

**Issue by Wesley-VanNeck** [Akarin-project/Akarin#16]
`[19:06:55 ERROR]: Error occurred while disabling AirBar v3.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/j256/ormlite/support/ConnectionSource
        at be.maximvdw.airbar.AirBar.onDisable(Unknown Source) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:266) ~[JavaPlugin.class:git-Akarin-"671c5fb"]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:350) [JavaPluginLoader.class:git-Akarin-"671c5fb"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:320) [JavaPluginLoader.class:git-Akarin-"671c5fb"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [SimplePluginManager.class:git-Akarin-"671c5fb"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395) [CraftServer.class:git-Akarin-"671c5fb"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344) [CraftServer.class:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:445) [MinecraftServer.class:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:1861) [MinecraftServer.class:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:344) [MinecraftServer.class:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:293) [DedicatedServer.class:git-Akarin-"671c5fb"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:git-Akarin-"671c5fb"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_172]
Caused by: java.lang.ClassNotFoundException: com.j256.ormlite.support.ConnectionSource
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_172]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:156) ~[PluginClassLoader.class:git-Akarin-"671c5fb"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:git-Akarin-"671c5fb"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_172]
        ... 13 more`

**Comment by Wesley-VanNeck** [comment]
and you say all plugins compatable ? well its great fork

**Comment by cakoyo** [comment]
ormlite... I guess you should ask the author
