### ISSUE TITLE
Skript + SkQuery not working.

### ISSUE THREAD

**Issue by satyrnhub** [Akarin-project/Akarin#175]
I'm running the latest version of Akarin, and when Skript and SkQuery attempt to load they error out.

Skript says:
`[19:12:24] [Server thread/ERROR]: Error occurred while enabling Skript v2.5-alpha3 (Is it up to date?)
java.lang.NoSuchFieldError: Legacy field ordinal: LEGACY_AIR
	at org.bukkit.craftbukkit.v1_15_R1.util.CraftLegacy.modern_ordinal(CraftLegacy.java:37) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at ch.njol.skript.aliases.MaterialRegistry.load(MaterialRegistry.java:66) ~[?:?]
	at ch.njol.skript.aliases.ItemData.<clinit>(ItemData.java:108) ~[?:?]
	at ch.njol.skript.aliases.Aliases.<clinit>(Aliases.java:142) ~[?:?]
	at ch.njol.skript.Skript.onEnable(Skript.java:405) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

SkQuery says:
`[19:12:25] [Server thread/INFO]: [SkQuery] Enabling SkQuery v3.6.5
[19:12:25] [Server thread/ERROR]: Error occurred while enabling SkQuery v3.6.5 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/classes/Parser
	at com.w00tmast3r.skquery.SkQuery.onEnable(SkQuery.java:29) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:364) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.classes.Parser
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 10 more
[19:12:25] [Server thread/INFO]: [SkQuery] Disabling SkQuery v3.6.5
[19:12:25] [Server thread/ERROR]: Error occurred while disabling SkQuery v3.6.5 (Is it up to date?)
java.lang.NoClassDefFoundError: ch/njol/skript/lang/SkriptEvent
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_242]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:757) ~[?:1.8.0_242]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:167) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:215) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:111) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	at com.w00tmast3r.skquery.SkQuery.onDisable(SkQuery.java:41) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:399) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:471) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:385) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:299) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:896) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]
Caused by: java.lang.ClassNotFoundException: ch.njol.skript.lang.SkriptEvent
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[?:1.8.0_242]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:171) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:100) ~[patched_1.15.2.jar:git-Akarin-"b7c5442"]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419) ~[?:1.8.0_242]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352) ~[?:1.8.0_242]
	... 21 more`

Plugins: `Plugins (28): AuctionHouse, CrazyEnchantments, CustomOreGen, EconomyShopGUI, Essentials, EssentialsChat, floodgate-bukkit, GriefPrevention, LuckPerms, mcMMO, MOTD, OldPVP, PlaceholderAPI, PlugMan, Sit, SkQuery, Skript, Sleep, SpigotLib, TAB, TimeIsMoney*, Trade, UltimateStacker, Vault, ViaVersion, VillagerOptimiser, Wild, WorldBorder`

Version: `git-Akarin-"b7c5442"`

I've also tried this with Tuinity, and it doesn't work. Unfortunately it only works with Paper/Spigot.

Any help?

**Comment by josephworks** [comment]
Does your server work on paper?

**Comment by satyrnhub** [comment]
Yep.

**Comment by josephworks** [comment]
Good to know

**Comment by josephworks** [comment]
please share full log

**Comment by satyrnhub** [comment]
https://pastebin.com/QzV2asDD

**Comment by josephworks** [comment]
SkQueary is working fine.

**Comment by satyrnhub** [comment]
Well, the /plugins output shows SkQuery in red.

**Comment by satyrnhub** [comment]
It also shows red for Skript

**Comment by josephworks** [comment]
It's working fine, but since Skript isn't loading in, it doesn't load.

**Comment by josephworks** [comment]
Create an issue at https://github.com/SkriptLang/Skript/issues

**Comment by satyrnhub** [comment]
Ahh, I see.

**Comment by satyrnhub** [comment]
So, they said to come back here.

**Comment by satyrnhub** [comment]
Any help?

**Comment by josephworks** [comment]
Hmm, like every other plugin works fine besides theirs. Looks like they have some fixing to do.

**Comment by josephworks** [comment]
I take that back

**Comment by josephworks** [comment]
Delete your skripts or fix them. Skript works with akarin and tuinity, so it looks like you have some fixing to do. This is not a skript or akarin issue.
