### ISSUE TITLE
java 10 not compatible

### ISSUE THREAD

**Issue by WesleyVanNeck** [Akarin-project/Akarin#19]
`[07:34:12 INFO]: [LaunchWrapper] Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[07:34:12 INFO]: [mixin] SpongePowered MIXIN Subsystem Version=0.7.10 
[07:34:12 INFO]: [mixin] FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[07:34:12 INFO]: [LaunchWrapper] Using primary tweak class name org.spongepowered.asm.launch.MixinTweaker
[07:34:13 INFO]: [mixin] Compatibility level set to JAVA_8
[07:34:13 INFO]: [LaunchWrapper] Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[07:34:13 INFO]: [LaunchWrapper] Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[07:34:13 INFO]: [LaunchWrapper] Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[07:34:13 WARN]: [mixin] Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/util/concurrent/locks/ReentrantReadWriteLock$ReadLock (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/lang/invoke/MethodHandles$Lookup (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
[07:34:13 WARN]: [mixin] Error loading class: java/io/File (java.lang.ClassCastException: java.base/jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to java.base/java.net.URLClassLoader)
java.lang.RuntimeException: java.lang.ClassNotFoundException: java.io.File
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:254)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:506)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:220)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:163)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:36)
Caused by: java.lang.ClassNotFoundException: java.io.File
        ... 19 more
Exception in thread "main" org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:521)
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:506)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:220)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Unknown Source)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:163)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:36)
Caused by: java.lang.RuntimeException: java.lang.ClassNotFoundException: java.io.File
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:682)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:670)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:267)
        at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:241)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1144)
        at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:254)
        at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:353)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.apply(MixinTransformer.java:724)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.applyMixins(MixinTransformer.java:703)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:509)
        ... 9 more
Caused by: java.lang.ClassNotFoundException: java.io.File
        ... 19 more`

**Comment by krusic22** [comment]
Anything higher than Java 8 (so 9,10,11) does not work or even compile.

**Comment by cakoyo** [comment]
current now support, just use java8
