### ISSUE TITLE
AAC Not Working On 1.12.2-0.4.2

### ISSUE THREAD

**Issue by ghost** [Akarin-project/Akarin#191]
Server Log Below:
[20:28:25 INFO]: [AAC] Attempting to inject into PlayerConnection
[20:28:26 ERROR]: Could not load 'plugins\[▒▒▒▒▒▒]AAC-4.4.1.jar' in folder 'plug                                                    ins'
org.bukkit.plugin.InvalidPluginException: java.lang.ExceptionInInitializerError
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j                                                    ava:131) ~[JavaPluginLoader.class:git-Akarin-5fe9361]
        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.                                                    java:333) ~[SimplePluginManager.class:git-Akarin-5fe9361]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager                                                    .java:255) ~[SimplePluginManager.class:git-Akarin-5fe9361]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.j                                                    ava:321) ~[CraftServer.class:git-Akarin-5fe9361]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.ja                                                    va:222) ~[DedicatedServer.class:git-Akarin-5fe9361]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.jav                                                    a:616) ~[MinecraftServer.class:git-Akarin-5fe9361]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_202]
Caused by: java.lang.ExceptionInInitializerError
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.jav                                                    a:82) ~[PluginClassLoader.class:git-Akarin-5fe9361]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j                                                    ava:127) ~[JavaPluginLoader.class:git-Akarin-5fe9361]
        ... 6 more
Caused by: java.lang.IllegalArgumentException: URI is not hierarchical
        at java.io.File.<init>(File.java:418) ~[?:1.8.0_202]
        at me.konsolas.aac.J.run(J.java) ~[?:?]
        at me.konsolas.aac.AAC.<clinit>(AAC.java) ~[?:?]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_202]
        at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_202]
        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.jav                                                    a:82) ~[PluginClassLoader.class:git-Akarin-5fe9361]
        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.j                                                    ava:127) ~[JavaPluginLoader.class:git-Akarin-5fe9361]
        ... 6 more

**Comment by ghost** [comment]
Just tested on all 1.12.2 versions, still not working

**Comment by josephworks** [comment]
>  in folder 'plug ins'

rename the folder to plugins

> Could not load 'plugins[▒▒▒▒▒▒]AAC-4.4.1.jar'

rename the jar to AAC-4.4.1.jar

**Comment by ghost** [comment]
> > in folder 'plug ins'
> 
> rename the folder to plugins
> 
> > Could not load 'plugins[▒▒▒▒▒▒]AAC-4.4.1.jar'
> 
> rename the jar to AAC-4.4.1.jar
Nope, Not the problem with the filename, all other plugins named in chinese works fine, it is showing up as a blur because git bash apperently does not support chinese, and the folder is named "plugins"

**Comment by josephworks** [comment]
Do you remember where you downloaded your jar from?

**Comment by ghost** [comment]
> Do you remember where you downloaded your jar from?

srry for the late reply, I Actually from a mirror.... think it was https://www.tcotp.cn/

**Comment by josephworks** [comment]
please update to https://github.com/Akarin-project/Akarin/releases/tag/1.12.2-R0.4.2

**Comment by ghost** [comment]
> please update to https://github.com/Akarin-project/Akarin/releases/tag/1.12.2-R0.4.2

still not working, exact same error

**Comment by josephworks** [comment]
Hmm, send new logs plz
