### ISSUE TITLE
[1.12.2] [Bug] AkarinSlackScheduler would fail sometime

### ISSUE THREAD

**Issue by ghost** [Akarin-project/Akarin#222]
[09:56:59 WARN]: Exception in thread "Akarin Slack Scheduler Thread" java.lang.IllegalArgumentException: timeout value is negative
[09:56:59 WARN]:        at java.lang.Thread.sleep(Native Method)
[09:56:59 WARN]:        at io.akarin.server.core.AkarinSlackScheduler.run(AkarinSlackScheduler.java:101)

in AkarinSlackScheduler.java:101 :

            try {
                Thread.sleep(100 - (System.currentTimeMillis() - startProcessTiming));
            } catch (InterruptedException interrupted) {
                ;
            }

Once AkarinSlackScheduler process something that takes more than 100ms then the argument in Thread.sleep() would be negative causing an exception and break the while loop.

**Comment by josephworks** [comment]
The PR has been merged

**Comment by josephworks** [comment]
Thank you for your contribution
