### ISSUE TITLE
new crash

### ISSUE THREAD

**Issue by Princess-of-Klaxosaurs** [Akarin-project/Akarin#36]
`[16:40:56 ERROR]: Could not pass event ChunkLoadEvent to HolographicDisplays v2.2.7-SNAPSHOT
org.bukkit.event.EventException: null
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:72) ~[EventExecutor$2.class:git-Akarin-"2def9e6"]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:78) ~[TimedEventExecutor.class:git-Akarin-"2def9e6"]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[RegisteredListener.class:git-Akarin-"2def9e6"]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:527) ~[SimplePluginManager.class:git-Akarin-"2def9e6"]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:512) ~[SimplePluginManager.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.Chunk.loadNearby(Chunk.java:1102) ~[Chunk.class:git-Akarin-"2def9e6"]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:59) ~[ChunkIOProvider.class:git-Akarin-"2def9e6"]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:16) ~[ChunkIOProvider.class:git-Akarin-"2def9e6"]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337) ~[AsynchronousExecutor.class:git-Akarin-"2def9e6"]
        at org.bukkit.craftbukkit.v1_12_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295) ~[AsynchronousExecutor.class:git-Akarin-"2def9e6"]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.lambda$syncChunkLoad$0(ChunkIOExecutor.java:18) ~[ChunkIOExecutor.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.MCUtil.ensureMain(MCUtil.java:536) ~[MCUtil.class:git-Akarin-"2def9e6"]
        at org.bukkit.craftbukkit.v1_12_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:18) ~[ChunkIOExecutor.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:164) ~[ChunkProviderServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:147) ~[ChunkProviderServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:143) ~[ChunkProviderServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.World.getType(World.java:892) ~[World.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.World.b(World.java:631) ~[World.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.World.c(World.java:536) ~[World.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.World.notifyAndUpdatePhysics(World.java:457) ~[World.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.World.setTypeAndData(World.java:436) ~[World.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.BlockFire.b(BlockFire.java:121) ~[BlockFire.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.WorldServer.a(WorldServer.java:808) ~[WorldServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.WorldServer.doTick(WorldServer.java:327) ~[WorldServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.tickWorld(MinecraftServer.java:1899) ~[MinecraftServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:1956) ~[MinecraftServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423) ~[DedicatedServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:768) ~[MinecraftServer.class:git-Akarin-"2def9e6"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[MinecraftServer.class:git-Akarin-"2def9e6"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]
Caused by: java.lang.IllegalStateException: zip file closed
        at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:1.8.0_181]
        at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:1.8.0_181]
        at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:1.8.0_181]
        at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:1.8.0_181]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:120) ~[PluginClassLoader.class:git-Akarin-"2def9e6"]
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:189) ~[JavaPluginLoader.class:git-Akarin-"2def9e6"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:115) ~[PluginClassLoader.class:git-Akarin-"2def9e6"]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:104) ~[PluginClassLoader.class:git-Akarin-"2def9e6"]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_181]
        at com.gmail.filoghost.holographicdisplays.listener.MainListener.processChunkLoad(MainListener.java:87) ~[?:?]
        at com.gmail.filoghost.holographicdisplays.listener.MainListener.onChunkLoad(MainListener.java:72) ~[?:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor271.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:70) ~[EventExecutor$2.class:git-Akarin-"2def9e6"]
        ... 29 more`

**Comment by Princess-of-Klaxosaurs** [comment]
it works on paper just fine

**Comment by cakoyo** [comment]
You can try to re-download the plugin and replace the old one

**Comment by cakoyo** [comment]
A fresh install on my local server works fine.

**Comment by Princess-of-Klaxosaurs** [comment]
@cakoyo all ready did that it did not work

**Comment by Princess-of-Klaxosaurs** [comment]
Its fixt
