### ISSUE TITLE
new crash

### ISSUE THREAD

**Issue by Princess-of-Klaxosaurs** [Akarin-project/Akarin#38]
`[12:45:49] [Server thread/ERROR]: Error occurred while enabling TitleManager v2.1.1 (Is it up to date?)
java.lang.IllegalArgumentException: null
	at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:565) ~[?:1.8.0_172]
	at io.puharesource.mc.titlemanager.scheduling.AsyncScheduler.scheduleRaw(AsyncScheduler.kt:54) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.registerAnnouncers(TitleManagerPlugin.kt:339) ~[?:?]
	at io.puharesource.mc.titlemanager.TitleManagerPlugin.onEnable(TitleManagerPlugin.kt:81) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Akarin-"0a59c8c"]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[JavaPluginLoader.class:git-Akarin-"0a59c8c"]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[SimplePluginManager.class:git-Akarin-"0a59c8c"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:398) ~[CraftServer.class:git-Akarin-"0a59c8c"]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[CraftServer.class:git-Akarin-"0a59c8c"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[MinecraftServer.`

**Comment by cakoyo** [comment]
When the `period` is given zero or negative, an `IllegalArgumentException` will throw from `ScheduledThreadPoolExecutor#scheduleAtFixedRate`, this won't be a server issue, just report to the plugin.
