### ISSUE TITLE
crash error

### ISSUE THREAD

**Issue by disqetow** [Akarin-project/Akarin#5]
This error crash server 

[08:40:50] [Server thread/ERROR]: Encountered an unexpected exception
java.util.ConcurrentModificationException: null
	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1442) ~[?:1.8.0_151]
	at java.util.HashMap$KeyIterator.next(HashMap.java:1466) ~[?:1.8.0_151]
	at net.minecraft.server.v1_12_R1.EntityTracker.updatePlayers(EntityTracker.java:180) ~[EntityTracker.class:git-Akarin-"02eda01"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:1858) ~[MinecraftServer.class:git-Akarin-"02eda01"]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:427) ~[DedicatedServer.class:git-Akarin-"02eda01"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:767) ~[MinecraftServer.class:git-Akarin-"02eda01"]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:665) [MinecraftServer.class:git-Akarin-"02eda01"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_151]

**Comment by disqetow** [comment]
https://pastebin.com/Y9SmntzK

**Comment by disqetow** [comment]
crash-report
https://pastebin.com/TDwyMjsH

**Comment by krusic22** [comment]
Last crash is caused by AntiBotDeluxe.

**Comment by disqetow** [comment]
But is first error crash server

**Comment by cakoyo** [comment]
Try latest version or #81cb233

**Comment by cakoyo** [comment]
I don't think this is caused by akarin, the part is not being multithreaded, I guess a plugin did async stuff incorrectly

**Comment by cakoyo** [comment]
Any way to reproduce?

**Comment by cakoyo** [comment]
Try latest build

**Comment by disqetow** [comment]
crash again:(
