### ISSUE TITLE
1.13: Anvil data error caused server crash

### ISSUE THREAD

**Issue by CBM1014** [Akarin-project/Akarin#50]
```
[19:10:30] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.fromData(CraftBlockData.java:449) ~[CraftBlockData.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.ContainerAnvil$2.a(ContainerAnvil.java:77) ~[ContainerAnvil$2.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.ContainerAnvil.shiftClick(ContainerAnvil.java:361) ~[ContainerAnvil.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.Container.a(Container.java:249) ~[Container.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2285) ~[PlayerConnection.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[PacketPlayInWindowClick.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[PacketPlayInWindowClick.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.mdb40d3f$lambda$ensureMainThread$0$0(PlayerConnectionUtils.java:523) ~[PlayerConnectionUtils.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:2070) ~[MinecraftServer.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[DedicatedServer.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:909) ~[MinecraftServer.class:git-Akarin-"72f3d31"]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:807) ~[MinecraftServer.class:git-Akarin-"72f3d31"]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[19:10:30] [Server thread/ERROR]: This crash report has been saved to: /root/cbm4/./crash-reports/crash-2018-08-12_19.10.30-server.txt
[19:10:30] [Server thread/INFO]: Stopping server
```
[Here is crash report.](https://public-readspace.oss-cn-beijing.aliyuncs.com/crash-reports/crash-2018-08-12_19.10.30-server.txt)

I couldn't reproduce this error in my local server, even though I used the same map and same plugins as the server which produced this error does. It's has become a magical error in my server these days.

**Comment by CBM1014** [comment]
I reproduce this error in my server just not. The error stack is the same. I can't get more information from reproducing it. Is there any way to show more details about this error？

**Comment by CBM1014** [comment]
@WhyDoWeWonder 
You can get the plugin list in the crash report.
And...damage value was removed in Minecraft 1.13.  

Plugins:
**CoreProtect** v2.15.1
**PermissionsEx** v1.23.4*
**MelonTPA** v1.0
**MelonHomes** vβ0.93 
**WhiteNoise** v1.0*
**Poster** v1.2β 
**MelonWhitelist** vβ0.01
**PlaceholderAPI** v2.8.7* 
**CBMUtils** vAlpha1.0 
**MiaoBoard** v2.4.1-git-1565c12dbc913d9376561a47636d109199bbaf20* 

MelonTPA，MelonHomes，MelonWhitelist and CBMUtils are plugins written by myself, I know there is no part about anvils.
MiaoBoard is a scoreboard plugin, I think there is no part about anvils either.
WhiteNoise is a plugin for count entities,
Poster is a plugin for reward active player in a Minecraft BBS in China, both written by cakoyo.
CoreProtect, PermissionsEx and PlaceholderAPI are common plugins, I think they can't cause the server crash.


In this way, I really have no idea about this crash.  ;w;

**Comment by CBM1014** [comment]
```
[10:15:45] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.fromData(CraftBlockData.java:497) ~[CraftBlockData.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.ContainerAnvil$2.a(ContainerAnvil.java:77) ~[ContainerAnvil$2.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.Container.a(Container.java:286) ~[Container.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2285) ~[PlayerConnection.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[PacketPlayInWindowClick.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[PacketPlayInWindowClick.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.mdc78429$lambda$ensureMainThread$0$0(PlayerConnectionUtils.java:523) ~[PlayerConnectionUtils.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:2127) ~[MinecraftServer.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[DedicatedServer.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:915) ~[MinecraftServer.class:git-Akarin-2593ab8]
	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:813) ~[MinecraftServer.class:git-Akarin-2593ab8]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
[10:15:45] [Server thread/ERROR]: This crash report has been saved to: /root/cbm4/./crash-reports/crash-2018-08-13_10.15.45-server.txt
[10:15:45] [Server thread/INFO]: Stopping server
```
[Here is crash report.](https://public-readspace.oss-cn-beijing.aliyuncs.com/crash-reports/crash-2018-08-13_10.15.45-server.txt)
The server crashed again. The error stack this time is a little different.
> Well, this is awkward.

**Comment by CBM1014** [comment]
I have some ideas about this issue.
Firstly, I think it is a random crash, a _magical error_
But the block which caused this crash is the anvil. Anvil is a block full of random and magic.
I found that the crashes have some points in common:
+ All the crashes happened on the player who is using Very Damaged Anvil
+ No anvil was been destroyed.

> With each use, an anvil has a 12% chance to become damaged – degrading one stage at a time, first becoming chipped, then damaged, then eventually destroyed.

Anvil's degrading will not cause the server crash.
My guess is that **eventually destroy an anvil in use** will cause the server crash.

**Comment by cakoyo** [comment]
@CBM1014 @SomeBottle Can you reproduce this in Spigot or Paper?

**Comment by CBM1014** [comment]
```
[23:59:00 FATAL]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NullPointerException
        at java.util.concurrent.FutureTask.report(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.get(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:199) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:986) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:428) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:914) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:812) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
Caused by: java.lang.NullPointerException
        at org.bukkit.craftbukkit.v1_13_R1.block.data.CraftBlockData.fromData(CraftBlockData.java:497) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.ContainerAnvil$2.a(ContainerAnvil.java:77) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.Container.a(Container.java:286) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:2274) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:33) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.PacketPlayInWindowClick.a(SourceFile:10) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:13) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_171]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_171]
        at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) ~[patched_1.13.jar:git-Paper-"8ad4c1e4"]
        ... 5 more
```
I **can** reproduce this error on paper, but Paper has no crash, just print the stack trace at the console.

**Comment by CBM1014** [comment]
In Spigot version _git-Spigot-2b0e71c-4a24108_, which I built just now, the anvil was eventually destroyed as expectation.
Paper version **git-Paper-"d285e05d"**, which I built just now too, still has this issue(no crash and print the stack trace at the console.).
Maybe I should report this issue to the upstream.

**Comment by CBM1014** [comment]
During the process of reproducing this error, Akarin crashed everytime.

**Comment by cakoyo** [comment]
Then you should report this to Paper. I'll investigate the different behaviour of packet execution.
