### ISSUE TITLE
ShopGUI plugin breaks with Akarin

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Akarin-project/Akarin#62]
`[01:15:49 ERROR]: Error occurred while enabling ShopGUIPlus v1.19.0 (Is it up to date?)
java.lang.IllegalArgumentException: null
        at net.brcdev.shopgui.util.ItemUtils.loadItemStackFromConfig(ItemUtils.java:127) ~[?:?]
        at net.brcdev.shopgui.settings.MenuSettings.load(MenuSettings.java:71) ~[?:?]
        at net.brcdev.shopgui.settings.MenuSettings.<init>(MenuSettings.java:22) ~[?:?]
        at net.brcdev.shopgui.settings.MenuWithItemSettings.<init>(MenuWithItemSettings.java:14) ~[?:?]
        at net.brcdev.shopgui.config.Settings.load(Settings.java:368) ~[?:?]
        at net.brcdev.shopgui.config.Settings.setConfig(Settings.java:147) ~[?:?]
        at net.brcdev.shopgui.ShopGuiPlugin.load(ShopGuiPlugin.java:188) ~[?:?]
        at net.brcdev.shopgui.ShopGuiPlugin.onEnable(ShopGuiPlugin.java:146) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[JavaPlugin.class:git-Akarin-"f73c20e"]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) ~[JavaPluginLoader.class:git-Akarin-"f73c20e"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) ~[SimplePluginManager.class:git-Akarin-"f73c20e"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:398) ~[CraftServer.class:git-Akarin-"f73c20e"]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:347) ~[CraftServer.class:git-Akarin-"f73c20e"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) ~[MinecraftServer.class:git-Akarin-"f73c20e"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:1862) ~[MinecraftServer.class:git-Akarin-"f73c20e"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) ~[MinecraftServer.class:git-Akarin-"f73c20e"]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289) ~[DedicatedServer.class:git-Akarin-"f73c20e"]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) ~[MinecraftServer.class:git-Akarin-"f73c20e"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_181]`

Help Please? Happens on startup

**Comment by cakoyo** [comment]
Check your config/plugin version or tell the plugin author, not a server issue.
