### ISSUE TITLE
ProtocolLib Error

### ISSUE THREAD

**Issue by Kyrobi** [Akarin-project/Akarin#70]
Build version tested:
- 6f1c0a6
- 4c4d318

With regards to the "Optimizes packet sending" patch, I think it might of messed up something regarding ProtocolLib (4.4.0).

Before the patch with version 6f1c0a6, the server would run without error. However, using 4c4d318, ProtocolLib spits out the follow error: https://pastebin.com/k3mjHiFC

Maybe add an option in akarin.yml to let's you select if you want to use the optimization?
As of currently, my console is just spammed with error from ProcotolLib every second. I ended up moving down to build 6f1c0a6.

**Comment by valenvaio** [comment]
[05:19:32] [Server thread/INFO]: This server is running Akarin version git-Akarin-"4c4d318" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)


[05:21:13] [Server thread/WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
[05:21:13] [Server thread/WARN]: [ProtocolLib] [ChannelInjector] Unable to send packet net.minecraft.server.v1_13_R2.PacketPlayOutTransaction@63728d2 to Fandorin
java.lang.IllegalArgumentException: argument type mismatch
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
        at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:658) ~[?:?]
        at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
        at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
        at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
        at me.vagdedes.spartan.i.b$1.a(Plib.java:75) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[mainworld.jar:git-Akarin-"4c4d318"]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[mainworld.jar:git-Akarin-"4c4d318"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[mainworld.jar:git-Akarin-"4c4d318"]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[mainworld.jar:git-Akarin-"4c4d318"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[mainworld.jar:git-Akarin-"4c4d318"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[mainworld.jar:git-Akarin-"4c4d318"]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

**Comment by Kyrobi** [comment]
> [05:19:32] [Server thread/INFO]: This server is running Akarin version git-Akarin-"4c4d318" (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
> 
> [05:21:13] [Server thread/WARN]: [ProtocolLib] Error filtering reports: java.lang.IllegalArgumentException: Cannot find report name for Unable to send packet %s to %s
> [05:21:13] [Server thread/WARN]: [ProtocolLib] [ChannelInjector] Unable to send packet net.minecraft.server.v1_13_R2.PacketPlayOutTransaction@63728d2 to Fandorin
> java.lang.IllegalArgumentException: argument type mismatch
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_191]
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_191]
> at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_191]
> at com.comphenix.protocol.injector.netty.ChannelInjector.invokeSendPacket(ChannelInjector.java:658) ~[?:?]
> at com.comphenix.protocol.injector.netty.ChannelInjector.sendServerPacket(ChannelInjector.java:640) ~[?:?]
> at com.comphenix.protocol.injector.netty.ProtocolInjector$4.sendServerPacket(ProtocolInjector.java:403) ~[?:?]
> at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:786) ~[?:?]
> at com.comphenix.protocol.injector.PacketFilterManager.sendServerPacket(PacketFilterManager.java:740) ~[?:?]
> at me.vagdedes.spartan.i.b$1.a(Plib.java:75) ~[?:?]
> at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[mainworld.jar:git-Akarin-"4c4d318"]
> at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[mainworld.jar:git-Akarin-"4c4d318"]
> at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1003) ~[mainworld.jar:git-Akarin-"4c4d318"]
> at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[mainworld.jar:git-Akarin-"4c4d318"]
> at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:938) ~[mainworld.jar:git-Akarin-"4c4d318"]
> at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:836) ~[mainworld.jar:git-Akarin-"4c4d318"]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

I realized that I mixed the two versions up in my original post. It's since been edited

**Comment by shinohara-rin** [comment]
https://github.com/Akarin-project/Akarin/blob/4c4d31875195c8bcb60acfdf8fc401a968969190/src/main/java/net/minecraft/server/PlayerConnection.java#L1496-L1516

blame this

**Comment by WesleyVanNeck** [comment]
I dont got any issues with protocollib

**Comment by cakoyo** [comment]
We added one more `sendPacket` method to support sending multiple packets at one time, it causes the error, rename the new method should resolve this error. I don't think an option will be needed, because the change should not cause any inconsistent behaviour.
