### ISSUE TITLE
Server Crash: Exception in server tick loop

### ISSUE THREAD

**Issue by Kyrobi** [Akarin-project/Akarin#72]
Currently running build: dbfd5f4
Going to update to the latest build tonight and see if it makes any difference.

In the span of 24 hours, the server has crashed 5 times. Went through the error messages and found this in the crash reports:  

`Time: 3/19/19, 5:03 PM
Description: Exception in server tick loop

java.lang.NullPointerException: Exception in server tick loop
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1575)
	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1500)
	at net.minecraft.server.v1_13_R2.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:376)
	at net.minecraft.server.v1_13_R2.EntityTracker.updatePlayers(EntityTracker.java:195)
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118)
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940)
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838)
	at java.base/java.lang.Thread.run(Thread.java:844)`

Edit: Also this `[21:05:28] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1575) ~[server.jar:git-Akarin-"78e8833"]
	at net.minecraft.server.v1_13_R2.PlayerConnection.sendPacket(PlayerConnection.java:1500) ~[server.jar:git-Akarin-"78e8833"]
	at net.minecraft.server.v1_13_R2.EntityTrackerEntry.updatePlayer(EntityTrackerEntry.java:376) ~[server.jar:git-Akarin-"78e8833"]
	at net.minecraft.server.v1_13_R2.EntityTracker.updatePlayers(EntityTracker.java:195) ~[server.jar:git-Akarin-"78e8833"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1118) ~[server.jar:git-Akarin-"78e8833"]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[server.jar:git-Akarin-"78e8833"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[server.jar:git-Akarin-"78e8833"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838) ~[server.jar:git-Akarin-"78e8833"]
	at java.lang.Thread.run(Thread.java:844) [?:?]`

And it is just today. So I'm hoping it's because of something wrong with the current build. 
I haven't changed any plugins... and it just randomly happened today. I'll update to the latest build and see what happens

**Comment by cakoyo** [comment]
Should be fixed in the latest build, reopen an issue if u encounter any new errors.
