### ISSUE TITLE
Citizens VerifyError

### ISSUE THREAD

**Issue by huynhqtienvtag** [Akarin-project/Akarin#73]
```
[14:00:15] [Server thread/WARN]: [Citizens] Task #105 for Citizens v2.0.24-SNAPSHOT (build 1626) generated an exception
java.lang.VerifyError: class net.citizensnpcs.nms.v1_13_R2.network.EmptyNetHandler overrides final method sendPacket.(Lnet/minecraft/server/v1_13_R2/Packet;)V
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_202]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_202]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_202]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:136) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:199) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:97) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_202]
	at net.citizensnpcs.nms.v1_13_R2.entity.HumanController.createEntity(HumanController.java:52) ~[?:?]
	at net.citizensnpcs.npc.AbstractEntityController.spawn(AbstractEntityController.java:41) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.spawn(CitizensNPC.java:209) ~[?:?]
	at net.citizensnpcs.npc.CitizensNPC.load(CitizensNPC.java:143) ~[?:?]
	at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:59) ~[?:?]
	at net.citizensnpcs.Citizens$3.run(Citizens.java:331) ~[?:?]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:82) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:449) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1005) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:940) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:838) ~[akarin-1.13.2.jar:git-Akarin-"58ed872"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_202]
```

**Comment by Satella1012** [comment]
same

**Comment by cakoyo** [comment]
Try the latest build, open a new issue if you still get this.
