### ISSUE TITLE
New version fails to start

### ISSUE THREAD

**Issue by krusic22** [Akarin-project/Akarin#8]
Build #127
` [15:19:11 INFO]: [LaunchWrapper] Loading tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:19:11 INFO]: [mixin] SpongePowered MIXIN Subsystem Version=0.7.8 Source=file:/root/krusic22/2SLO4U/spigot.jar Service=LaunchWrapper Env=UNKNOWN
[15:19:11 INFO]: [mixin] FML platform manager could not load class cpw.mods.fml.relauncher.CoreModManager. Proceeding without FML support.
[15:19:11 INFO]: [LaunchWrapper] Using primary tweak class name org.spongepowered.asm.launch.MixinTweaker
[15:19:11 INFO]: [mixin] Compatibility level set to JAVA_8
[15:19:11 INFO]: [LaunchWrapper] Calling tweak class org.spongepowered.asm.launch.MixinTweaker
[15:19:11 INFO]: [LaunchWrapper] Loading tweak class name org.spongepowered.asm.mixin.EnvironmentStateTweaker
[15:19:11 INFO]: [LaunchWrapper] Calling tweak class org.spongepowered.asm.mixin.EnvironmentStateTweaker
[15:19:11 FATAL]: [mixin] Mixin prepare failed preparing core.MixinPlayerList in mixins.akarin.core.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException java.lang.ClassNotFoundException: The specified mixin 'io.akarin.server.mixin.core.MixinPlayerList' was not found
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.ClassNotFoundException: The specified mixin 'io.akarin.server.mixin.core.MixinPlayerList' was not found
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:795) ~[spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569) ~[spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:509) ~[spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647) [spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572) [spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548) [spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451) [spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72) [spigot.jar:git-Akarin-"2b49aba"]
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:505) [spigot.jar:git-Akarin-"2b49aba"]
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:219) [spigot.jar:git-Akarin-"2b49aba"]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [?:1.8.0_172]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [?:1.8.0_172]
        at java.lang.Class.forName0(Native Method) ~[?:1.8.0_172]
        at java.lang.Class.forName(Class.java:348) [?:1.8.0_172]
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:156) [spigot.jar:git-Akarin-"2b49aba"]
        at net.minecraft.launchwrapper.Launch.main(Launch.java:34) [spigot.jar:git-Akarin-"2b49aba"]
Caused by: java.lang.ClassNotFoundException: The specified mixin 'io.akarin.server.mixin.core.MixinPlayerList' was not found
        at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1163) ~[spigot.jar:git-Akarin-"2b49aba"]
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:788) ~[spigot.jar:git-Akarin-"2b49aba"]
        ... 15 more
Exception in thread "main" org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [mixins.akarin.core.json:core.MixinPlayerList] from phase [DEFAULT] in config [mixins.akarin.core.json] FAILED during PREPARE
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinError(MixinTransformer.java:779)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.handleMixinPrepareError(MixinTransformer.java:728)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:650)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.select(MixinTransformer.java:572)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.checkSelect(MixinTransformer.java:548)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:451)
        at org.spongepowered.asm.mixin.transformer.Proxy.transform(Proxy.java:72)
        at net.minecraft.launchwrapper.LaunchClassLoader.runTransformers(LaunchClassLoader.java:505)
        at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:219)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.minecraft.launchwrapper.Launch.launch(Launch.java:156)
        at net.minecraft.launchwrapper.Launch.main(Launch.java:34)
Caused by: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: java.lang.ClassNotFoundException: The specified mixin 'io.akarin.server.mixin.core.MixinPlayerList' was not found
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:795)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:569)
        at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:509)
        at org.spongepowered.asm.mixin.transformer.MixinTransformer.prepareConfigs(MixinTransformer.java:647)
        ... 12 more
Caused by: java.lang.ClassNotFoundException: The specified mixin 'io.akarin.server.mixin.core.MixinPlayerList' was not found
        at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1163)
        at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:788)
        ... 15 more
`

**Comment by cakoyo** [comment]
A typo, I will fix it
