### ISSUE TITLE
Player auto disconnected (Randomly)

### ISSUE THREAD

**Issue by HeliosOps** [Akarin-project/Akarin#80]
Hello. My server is running the latest version of Waterfall and Akarin 1.13.2.
Then player will auto disconnected in random time.

Client received error: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

Then I open server to debug mode then get this error log:

[19:50:59] [Netty Server IO #0/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[19:50:59] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector$2.channelRead(ChannelInjector.java:248)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1434)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:965)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:647)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:582)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:499)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:461)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:50:59] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[19:50:59] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[19:50:59] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:490)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[19:50:59] [Netty Server IO #0/WARN]: 	... 30 more
[19:50:59] [Netty Server IO #0/WARN]: Caused by: java.io.IOException: Packet 0/0 (PacketPlayInTeleportAccept) was larger than I expected, found 102 bytes extra whilst reading packet 0
[19:50:59] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_13_R2.PacketDecoder.decode(SourceFile:42)
[19:50:59] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[19:50:59] [Netty Server IO #0/WARN]: 	... 33 more
[19:50:59] [Netty Server IO #0/WARN]: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:377)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.ChannelInboundHandlerAdapter.channelInactive(ChannelInboundHandlerAdapter.java:75)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.timeout.IdleStateHandler.channelInactive(IdleStateHandler.java:277)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.fireChannelInactive(AbstractChannelHandlerContext.java:224)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelInactive(DefaultChannelPipeline.java:1429)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:231)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.DefaultChannelPipeline.fireChannelInactive(DefaultChannelPipeline.java:947)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.AbstractChannel$AbstractUnsafe$8.run(AbstractChannel.java:822)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:465)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
[19:50:59] [Netty Server IO #0/WARN]: 	at java.lang.Thread.run(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: Caused by: java.lang.RuntimeException: An internal error occured.
[19:50:59] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:20)
[19:50:59] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.injector.netty.ChannelInjector.decode(ChannelInjector.java:490)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
[19:50:59] [Netty Server IO #0/WARN]: 	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
[19:50:59] [Netty Server IO #0/WARN]: 	... 30 more
[19:50:59] [Netty Server IO #0/WARN]: Caused by: java.io.IOException: Packet 0/0 (PacketPlayInTeleportAccept) was larger than I expected, found 97 bytes extra whilst reading packet 0
[19:50:59] [Netty Server IO #0/WARN]: 	at net.minecraft.server.v1_13_R2.PacketDecoder.decode(SourceFile:42)
[19:50:59] [Netty Server IO #0/WARN]: 	at sun.reflect.GeneratedMethodAccessor13.invoke(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[19:50:59] [Netty Server IO #0/WARN]: 	at com.comphenix.protocol.reflect.accessors.DefaultMethodAccessor.invoke(DefaultMethodAccessor.java:16)
[19:50:59] [Netty Server IO #0/WARN]: 	... 33 more
[19:50:59] [Server thread/INFO]: xXXXXXXx lost connection: Internal Exception: io.netty.handler.codec.DecoderException: java.lang.RuntimeException: An internal error occured.

**Comment by shinohara-rin** [comment]
Looks like a malformed packets problem to me, have you installed any.... weird plugin that alters minecraft networking protocol?

**Comment by shinohara-rin** [comment]
Does this happens to all players, or a particular one?

**Comment by HeliosOps** [comment]
Plugins (13): BungeeTabListPlus, Essentials, EssentialsAntiBuild, EssentialsChat, EssentialsGeoIP, EssentialsProtect, EssentialsSpawn, GroupManager, ProtocolLib, SkinsRestorer, Vault, WorldEdit, WorldGuard

Its happened to all players.

**Comment by shinohara-rin** [comment]
It seems there's some problem around `PacketPlayInTeleportAccept` packet, I don't know, maybe related to packet compression i guess?

**Comment by shinohara-rin** [comment]
a packet capture would help determining if it's caused by malformed packets. maybe you can try to run the server without waterfall first?
