### ISSUE TITLE
error on join

### ISSUE THREAD

**Issue by KonoromiHimaries** [Akarin-project/Akarin#81]
timings
https://timings.aikar.co/?id=888ca767b17a453482e22563942e2b25

logs
```
[03:56:42 WARN]: Failed to handle packet for /192.168.7.2:3867
java.lang.NullPointerException: null
        at me.lucko.luckperms.bukkit.calculator.DefaultsProcessor.hasPermission(DefaultsProcessor.java:48) ~[?:?]
        at me.lucko.luckperms.common.calculator.PermissionCalculator.apply(PermissionCalculator.java:106) ~[?:?]
        at me.lucko.luckperms.common.calculator.PermissionCalculator.apply(PermissionCalculator.java:46) ~[?:?]
        at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(Unknown Source) ~[?:1.8.0_201]
        at me.lucko.luckperms.common.util.LoadingMap.get(LoadingMap.java:67) ~[?:?]
        at me.lucko.luckperms.common.calculator.PermissionCalculator.getPermissionValue(PermissionCalculator.java:85) ~[?:?]
        at me.lucko.luckperms.common.cacheddata.type.PermissionCache.getPermissionValue(PermissionCache.java:117) ~[?:?]
        at me.lucko.luckperms.bukkit.inject.permissible.LPPermissible.hasPermission(LPPermissible.java:167) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.entity.CraftHumanEntity.hasPermission(CraftHumanEntity.java:214) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:136) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.CommandListenerWrapper.hasPermission(CommandListenerWrapper.java:126) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.CommandForceload.lambda$a$2(CommandForceload.java:26) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at com.mojang.brigadier.tree.CommandNode.canUse(CommandNode.java:78) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.CommandDispatcher.a(CommandDispatcher.java:287) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.CommandDispatcher.a(CommandDispatcher.java:254) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:1210) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.PlayerList.f(PlayerList.java:859) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.PlayerList.a(PlayerList.java:171) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.joinGame(SpigotLoginListenerPlay.java:140) ~[?:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.tryJoin(AbstractLoginListenerPlay.java:123) ~[?:?]
        at protocolsupport.protocol.packet.handler.AbstractLoginListenerPlay.loginTick(AbstractLoginListenerPlay.java:85) ~[?:?]
        at protocolsupport.zplatform.impl.spigot.network.handler.SpigotLoginListenerPlay.tick(SpigotLoginListenerPlay.java:81) ~[?:?]
        at net.minecraft.server.v1_13_R2.NetworkManager.a(NetworkManager.java:351) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.ServerConnection.c(ServerConnection.java:150) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1138) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[akarin-1.13.2-b55.jar:git-Akarin-"2dd8f6f"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
```

ss
![2019-04-01-Window](https://user-images.githubusercontent.com/5884000/55299479-6d941f80-5433-11e9-80f9-68c236a31ba9.png)

**Comment by cakoyo** [comment]
Fixed in the latest build, thanks for reporting.
