### ISSUE TITLE
FactionsUUID error

### ISSUE THREAD

**Issue by WhyDoWeWonder** [Akarin-project/Akarin#88]
`[18:42:46 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'f' in plugin Factions v1.6.9.5-U0.3.0-b136
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:48) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:151) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at org.bukkit.craftbukkit.v1_13_R2.CraftServer.dispatchCommand(CraftServer.java:735) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.PlayerConnection.handleCommand(PlayerConnection.java:1864) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.PlayerConnection.a(PlayerConnection.java:1668) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:15) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) ~[?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(Unknown Source) ~[?:1.8.0_211]
        at net.minecraft.server.v1_13_R2.SystemUtils.a(SystemUtils.java:108) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1023) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:440) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:945) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:842) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]
Caused by: java.lang.RuntimeException: The operation to load user data for 'f9034e10-9cd0-401d-9cf3-f3cf5439d618' was cancelled by LuckPerms. This is NOT a bug.
The lookup request was made on the main server thread. It is not safe to execute a request to
load username data from the database in this context.
If you are a plugin author, please consider making your request asynchronously.
Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true
in the LP config, but should consider the consequences (lag) before doing so.
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.lookupUser(LuckPermsVaultPermission.java:143) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.LuckPermsVaultPermission.userGetPrimaryGroup(LuckPermsVaultPermission.java:249) ~[?:?]
        at me.lucko.luckperms.bukkit.vault.AbstractVaultPermission.getPrimaryGroup(AbstractVaultPermission.java:384) ~[?:?]
        at com.massivecraft.factions.P.getPrimaryGroup(P.java:432) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagReplacer.getValue(TagReplacer.java:161) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.parsePlain(TagUtil.java:49) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.tipPlayer(TagUtil.java:266) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.getFancy(TagUtil.java:229) ~[?:?]
        at com.massivecraft.factions.zcore.util.TagUtil.parseFancy(TagUtil.java:93) ~[?:?]
        at com.massivecraft.factions.cmd.CmdShow.perform(CmdShow.java:90) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:73) ~[?:?]
        at com.massivecraft.factions.cmd.FCommand.execute(FCommand.java:59) ~[?:?]
        at com.massivecraft.factions.cmd.FCmdRoot.onCommand(FCmdRoot.java:217) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[akarin-1.13.2.jar:git-Akarin-"0231984"]
        ... 15 more`

**Comment by cakoyo** [comment]
> The operation to load user data for 'f9034e10-9cd0-401d-9cf3-f3cf5439d618' was cancelled by LuckPerms. This is NOT a bug. The lookup request was made on the main server thread. It is not safe to execute a request to load username data from the database in this context. If you are a plugin author, please consider making your request asynchronously. Alternatively, server admins can disable this catch by setting 'vault-unsafe-lookups' to true in the LP config, but should consider the consequences (lag) before doing so.
