### ISSUE TITLE
1.13:bug

### ISSUE THREAD

**Issue by roughanddai** [Akarin-project/Akarin#89]

**Comment by roughanddai** [comment]
[authlib-injector.launch] [信息] Version: 1.1.26-41a7a47
[authlib-injector.config] [信息] API root: https://skin.prinzeugen.net/api/yggdrasil/
[authlib-injector.transform] [信息] Transformed [io.akarin.server.core.AkarinGlobalConfig] with [Constant URL Transformer]
Exception in thread "main" java.lang.NullPointerException
	at org.bukkit.Bukkit.getLogger(Bukkit.java:656)
	at io.akarin.server.core.AkarinGlobalConfig.init(AkarinGlobalConfig.java:36)
	at org.bukkit.craftbukkit.Main.main(Main.java:24)

**Comment by cakoyo** [comment]
Fixed in the latest build, however, this error will only occur when failed to load the config, and you should be able to find more info from the error log after updating.
