### ISSUE TITLE
1.13:it is my question or bug?

### ISSUE THREAD

**Issue by roughanddai** [Akarin-project/Akarin#91]
18:52:23] [main/INFO]: Loaded 0 recipes
[18:52:23] [Server thread/INFO]: Starting minecraft server version 1.13.2
[18:52:23] [Server thread/INFO]: Loading properties
[18:52:23] [Server thread/WARN]: Failed to load server.properties
java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
	at java.util.Properties.loadConvert(Unknown Source) ~[?:1.8.0_211]
	at java.util.Properties.load0(Unknown Source) ~[?:1.8.0_211]
	at java.util.Properties.load(Unknown Source) ~[?:1.8.0_211]
	at net.minecraft.server.v1_13_R2.PropertyManager.<init>(PropertyManager.java:26) ~[akarin-1.13.2-b84.jar:git-Akarin-"2215a2d"]
	at net.minecraft.server.v1_13_R2.PropertyManager.<init>(PropertyManager.java:51) ~[akarin-1.13.2-b84.jar:git-Akarin-"2215a2d"]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:149) ~[akarin-1.13.2-b84.jar:git-Akarin-"2215a2d"]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:790) ~[akarin-1.13.2-b84.jar:git-Akarin-"2215a2d"]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_211]

my English is poor so plz allow me use Chinese
在这个错误发生之前，我照着维基的方法输入/uu00A7byes使我的字体yes更改颜色，然后我发现在更改后会出现这个bug，它使我的配置文件被替换了。当然我不确定这是不是一个bug，暂时没有用其他的服务端测试。

**Comment by WesleyVanNeck** [comment]
Your server.properties is currupt Malformed

**Comment by WesleyVanNeck** [comment]
This is not a bug

**Comment by cakoyo** [comment]
請嘗試重置 server.properties 文件。

**Comment by WhyDoWeWonder** [comment]
If this is still a problem attach your server.properties file and I can fix it for you.
