### ISSUE TITLE
Akarin 1.12.2 - 0.4.2 LTS Release 

### ISSUE THREAD

**Issue by disqetow** [Akarin-project/Akarin#97]
[20:31:27] [Craft Scheduler Thread - 9/ERROR]: [MythicMobs] [31m[SCHEDULER] Exception thrown whilst executing task[37m
[20:31:27] [Craft Scheduler Thread - 9/WARN]: java.lang.IllegalStateException: Calling Timings from Async Operation
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at co.aikar.timings.UnsafeTimingHandler.checkThread(UnsafeTimingHandler.java:36)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at co.aikar.timings.UnsafeTimingHandler.startTiming(UnsafeTimingHandler.java:42)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at co.aikar.timings.TimingHandler.startTimingIfSync(TimingHandler.java:534)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at io.lumine.utils.timingslib.MinecraftTiming.startTiming(MinecraftTiming.java:16)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at io.lumine.utils.tasks.Scheduler$TaskImpl.run(Scheduler.java:433)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:31:27] [Craft Scheduler Thread - 9/WARN]: 	at java.lang.Thread.run(Unknown Source)
[20:31:27] [Craft Scheduler Thread - 0/INFO]: [PlaceholderAPI] 148 placeholder expansions are available on the cloud.
[20:31:27] [Craft Scheduler Thread - 0/INFO]: [PlaceholderAPI] 0 expansions you use have updates.
[20:31:32] [Craft Scheduler Thread - 13/ERROR]: [MythicMobs] [31m[SCHEDULER] Exception thrown whilst executing task[37m
[20:31:32] [Craft Scheduler Thread - 13/WARN]: java.lang.IllegalStateException: Calling Timings from Async Operation
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at co.aikar.timings.UnsafeTimingHandler.checkThread(UnsafeTimingHandler.java:36)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at co.aikar.timings.UnsafeTimingHandler.startTiming(UnsafeTimingHandler.java:42)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at co.aikar.timings.TimingHandler.startTimingIfSync(TimingHandler.java:534)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at io.lumine.utils.timingslib.MinecraftTiming.startTiming(MinecraftTiming.java:16)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at io.lumine.utils.tasks.Scheduler$TaskImpl.run(Scheduler.java:433)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[20:31:32] [Craft Scheduler Thread - 13/WARN]: 	at java.lang.Thread.run(Unknown Source)

**Comment by WhyDoWeWonder** [comment]
Thank you for your report, can you please give me more information?
Does this happen on paper?
Does this happen on the latest Akarin 1.12.2 build?
What version of MythicMobs are you using?
Your plugins list.

**Comment by disqetow** [comment]
Akarin not support mythicmobs,when I use mythicmobs egg spawn mobs,It will crash by itemstack.
It didnt crash at paperspigot. And I think Akarin 1.12.2 - 0.4.2 is latest build.
There are two crash with Mythicmobs.

**Comment by disqetow** [comment]
https://pastebin.com/fSGPbwj6

**Comment by disqetow** [comment]
https://pastebin.com/fSGPbwj6

**Comment by WhyDoWeWonder** [comment]
To clarify if there's any confusion here:

Akarin 1.12.2  - 0.4.2 supports up to MythicMobs v4.5.1, which can be downloaded here: https://media.forgecdn.net/files/2658/395/Mythicmobs-4.5.1.jar 

Using this version of MythicMobs will fix your issue; however, you may choose to use a newer version, but you will get a lot of console spam. This will **not** affect the functionality of Mythicmobs or Akarin, but it can be quite annoying. There is also no recent version of Mythicmobs that crashes Akarin.

**Comment by josephworks** [comment]
Issue resolved
